services:
  db:
    image: mysql:8.0
    container_name: scrapper_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scrap_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: wordpress_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: scrapper_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/scrapper_db
    depends_on:
      - db

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: scrapper_scraper
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/scrapper_db
    volumes:
      - ./scraper:/app
    depends_on:
      - db

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: scrap_db
      WORDPRESS_REDIS_HOST: redis
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
      - redis

volumes:
  db_data:
  wordpress_data:
  redis_data:
