services:
  redis:
    image: redis:alpine
    container_name: wordpress_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: scrapper_api
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:password@db/scrapper_db
    volumes:
      - ./api:/app
      - /app/node_modules

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: scrapper_scraper
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/scrapper_db
    volumes:
      - ./scraper:/app

volumes:
  redis_data:
