services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: scrapper_api
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:password@db/scrapper_db
    volumes:
      - ./api:/app
      - /app/node_modules

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: scrapper_scraper
    env_file:
      - ./scraper/.env
    volumes:
      - ./scraper:/app
