export const enum ExceptionCodeEnum {
  MYSQL_SERVICE__CONN_ERR = 'MYSQL-SERVICE-010-CONER',
  MYSQL_SERVICE__QUERY_ERR = 'MYSQL-SERVICE-020-QERER',

  EXPRESS_APP__START_ERR = 'EXPRESS-APP-010-STRER',

  AXIOS_CONN__AGENT_ERR = 'AXIOS-CONNECTION-010-AGTER',
  AXIOS_CONN__JWS_ERR = 'AXIOS-CONNECTION-020-JWSER',
}
